const themes = [
  {
    name: "Комната",
    words: [
      {
        word: "Комната",
        translation: "room",
        pronunciation: "рум",
        description: "",
        description_translation: "",
        image: "./img/dictionary/room.avif",
      },
      {
        word: "Дверь",
        translation: "door",
        pronunciation: "дор",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_00-58-57.jpg",
      },
      {
        word: "Окно",
        translation: "window",
        pronunciation: "виндов",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-07-36.jpg",
      },
      {
        word: "Подоконник",
        translation: "windowsill",
        pronunciation: "виндовсил",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-08-11.jpg",
      },
      {
        word: "Кровать",
        translation: "bed",
        pronunciation: "бэд",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-08-43.jpg",
      },
      {
        word: "Подушка",
        translation: "pillow",
        pronunciation: "пилоув",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-08-58.jpg",
      },
      {
        word: "Одеяло",
        translation: "quilt",
        pronunciation: "куилт",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-09-11.jpg",
      },
      {
        word: "Простыня",
        translation: "sheet",
        pronunciation: "шит",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-09-26.jpg",
      },
      {
        word: "Стол",
        translation: "table",
        pronunciation: "тєйбел",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-09-45.jpg",
      },
      {
        word: "Стул",
        translation: "chair",
        pronunciation: "чє",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-10-00.jpg",
      },
      {
        word: "Розетка",
        translation: "socket",
        pronunciation: "сокэт",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-10-28.jpg",
      },
      {
        word: "Выключатель",
        translation: "switch",
        pronunciation: "свич",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-10-43.jpg",
      },
      {
        word: "Ковер",
        translation: "carpet",
        pronunciation: "карпет",
        description: ".",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-10-56.jpg",
      },
      {
        word: "Пол",
        translation: "floor",
        pronunciation: "флор",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-11-10.jpg",
      },
      {
        word: "Шкаф",
        translation: "wardrobe",
        pronunciation: "вардроб",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-11-49.jpg",
      },
      {
        word: "Кресло",
        translation: "armchair",
        pronunciation: "эмче",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-11-59.jpg",
      },
      {
        word: "Тумба",
        translation: "badside table",
        pronunciation: "бэдсайд тэйбел",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-22-32.jpg",
      },
      {
        word: "Зеркало",
        translation: "mirror",
        pronunciation: "мирор",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-12-43.jpg",
      },
      {
        word: "Лампа",
        translation: "lamp",
        pronunciation: "ламп",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-13-04.jpg",
      },
      {
        word: "Холодильник",
        translation: "fridge",
        pronunciation: "фридж",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-22-02.jpg",
      },
    ],
  },
  {
    name: "Кухня",
    words: [
      {
        word: "Ложка",
        translation: "spoon",
        pronunciation: "спун",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-28-15.jpg",
      },
      {
        word: "Вилка",
        translation: "fork",
        pronunciation: "фок",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-28-28.jpg",
      },
      {
        word: "Нож",
        translation: "knife",
        pronunciation: "найф",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-28-38.jpg",
      },
      {
        word: "Кастрюля",
        translation: "pot",
        pronunciation: "пот",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-28-58.jpg",
      },
      {
        word: "Чайник",
        translation: "kettle",
        pronunciation: "кэтл",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-29-33.jpg",
      },
      {
        word: "Сковорода",
        translation: "pan",
        pronunciation: "пэн",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-29-49.jpg",
      },
      {
        word: "Чашка",
        translation: "cup",
        pronunciation: "кап",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-30-02.jpg",
      },
      {
        word: "Тарелка",
        translation: "plate",
        pronunciation: "плэйт",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-30-13.jpg",
      },
      {
        word: "Глубокая тарелка",
        translation: "bowl",
        pronunciation: "боул",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-30-26.jpg",
      },
    ],
  },
  {
    name: "Технологии",
    words: [
      {
        word: "Телефон",
        translation: "phone",
        pronunciation: "фон",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-41-53.jpg",
      },
      {
        word: "Наушники",
        translation: "headphones",
        pronunciation: "хэдфонс",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-41-40.jpg",
      },
      {
        word: "Зарядка",
        translation: "phone charger",
        pronunciation: "фон чарджер",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-41-27.jpg",
      },
      {
        word: "Смарт-часы",
        translation: "smartwatch",
        pronunciation: "сматрвотч",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-42-51.jpg",
      },
      {
        word: "Чехол",
        translation: "phone case",
        pronunciation: "фон кэйс",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-40-35.jpg",
      },
      {
        word: "Ноутбук",
        translation: "laptop",
        pronunciation: "лэптоп",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-39-53.jpg",
      },
    ],
  },

  {
    name: "Одежда",
    words: [
      {
        word: "Очки",
        translation: "glasses",
        pronunciation: "глэсес",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-50-25.jpg",
      },
      {
        word: "Футболка",
        translation: "t-shirt",
        pronunciation: "ти шёрт",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-50-15.jpg",
      },
      {
        word: "Джинсы",
        translation: "jeans",
        pronunciation: "джынс",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-50-03.jpg",
      },
      {
        word: "Платье",
        translation: "dress",
        pronunciation: "дресс",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-49-52.jpg",
      },
      {
        word: "Топ",
        translation: "top",
        pronunciation: "топ",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-49-40.jpg",
      },
      {
        word: "Свитер",
        translation: "sweater",
        pronunciation: "свэтэ",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-49-28.jpg",
      },
      {
        word: "Блузка",
        translation: "blouse",
        pronunciation: "блауз",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-49-18.jpg",
      },
      {
        word: "Ботинки",
        translation: "boots",
        pronunciation: "бутс",
        description: "",
        description_translation: "",
        image: "./img/dictionaryphoto_2024-10-06_01-49-09.jpg",
      },
      {
        word: "Шорты",
        translation: "shorts",
        pronunciation: "шортс",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-48-58.jpg",
      },
      {
        word: "Кроссовки",
        translation: "sneakers",
        pronunciation: "сникэрс",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-48-49.jpg",
      },
      {
        word: "Балетки",
        translation: "flats",
        pronunciation: "флэтс",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-48-38.jpg",
      },
      {
        word: "Сумка",
        translation: "bag",
        pronunciation: "бэг",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-48-28.jpg",
      },
      {
        word: "Рюкзак",
        translation: "backpack",
        pronunciation: "бэкпэк",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-48-05.jpg",
      },
      {
        word: "Тапочки",
        translation: "slippers",
        pronunciation: "слипэрс",
        description: "",
        description_translation: "",
        image: "./img/dictionary/photo_2024-10-06_01-47-53.jpg",
      },
    ],
  },
];
